### ISSUE TITLE
Item Tracker: Make the placement of the item tracker more manageable

### ISSUE THREAD

**Issue by marclemieux64** [briaguya-ai/rando-issue-tracker#127]
so I really like the placement menu control and would like to have a similar control on it. currently we can space item or change de size but we cannot move content of the tracker inside the tracker itself.

**Comment by briaguya-ai** [comment]
could you explain what you mean a little more? what content within the tracker would you like to be able to move?

**Comment by marclemieux64** [comment]
Oh yeah sure when I talk about the content. I talk about the array of icon for each item.  The way I imagine it is that array we see it as a block that we can move around if we dock it or pin it.

**Comment by aMannus** [comment]
So tell me if I'm understanding this incorrectly, but are you asking for just moving the icons within the Item Tracker window? So basically just adjust the margins?

So instead of this: 
![image](https://user-images.githubusercontent.com/4244591/177944763-23fef1ec-3af9-4164-b8f6-ea292f2b8927.png)

It could be this: 
![image](https://user-images.githubusercontent.com/4244591/177945007-02c8d6a4-cfd1-4613-b8f8-062a82a770fa.png)

**Comment by marclemieux64** [comment]
![Screenshot_27(edited)](https://user-images.githubusercontent.com/93109559/177962490-66998a37-5307-4269-b5b8-731c2fd8a035.png)  with  the placement menu I would be able to place it like this
.

**Comment by aMannus** [comment]
Closed, continues in #126
